defaults:
  impedance_ohms: 50  # for future VNA work
  output_root: "./data"

rtlsdr:
  sample_rate: 2048000
  gain: "auto"
  ppm: 0

scan:
  start_hz: 88000000
  stop_hz: 108000000
  bin_hz: 25000
  dwell_ms: 30
  average_count: 5

profiles:
  antennas_file: "config/profiles/antennas.yaml"
  locations_file: "config/profiles/locations.yaml"

exports:
  csv: true
  json_run_report: true
